name: ci-linux
on:
  push:
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # install deps.
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsystemd-dev

      - name: Install system dependencies
        uses: input-output-hk/actions/base@latest


      - uses: haskell-actions/setup@v2
        id: cabal-setup
        with:
          ghc-version: '9.6.6'
          cabal-version: '3.10.3.0'

      - uses: actions/checkout@v4

      - name: Cache .cabal
        uses: actions/cache@v3
        with:
          path: ${{ steps.cabal-setup.outputs.cabal-store }}
          key: cabal-${{ hashFiles('cabal.project') }}

      - name: Build dependencies for integration test
        run: |
          cabal update
          cabal install -j cardano-node-10.1.4 cardano-cli --overwrite-policy=always
          cabal install -j convex-wallet --overwrite-policy=always
          echo "/home/runner/.cabal/bin" >> $GITHUB_PATH

      - name: build & test
        run: |
          cabal build -j all
          cabal test all

